#include "nu_ska_jag_supa.typ"
#include "gass_te_dej.typ"
#include "yesterday.typ"
// #include "dance macabre"
#include "berkeley_california.typ"
#include "bruces_philosophers_song.typ"
#include "fru_svenssons_lyckliga_karl.typ"
#include "brev_fran_campus.typ"
#include "en_matematiker.typ"
#include "gaffas_visa.typ"
#include "fyllevisa.typ"
#include "lasa_matematik.typ"
#include "kopparslagaren.typ"
#include "nuskaviklamma.typ"
#include "1_2_45.typ"
#include "sangen_till_kvinnan.typ"
// #include "systeme_international.typ"
#include "systeme_periodique.typ"
