[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "audio"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
rocket = { version = "=0.5.0-rc.3", features = ["json"] }
serde_with = "3.24.0"
