
#include "betlehems_stjarna.typ"
#include "den_blomstertid_nu_kommer.typ"
#include "hej_tomtegubbar.typ"
#include "idas_sommarvisa.typ"
#include "kraftan_ar_ett_lackert_djur.typ"
#include "kraftor_atas.typ"
#include "langtan_till_landet.typ"
#include "lucia_ver1.typ"
#include "nu_ar_det_jul_igen.typ"
#include "nu_gronskar_det.typ"
#include "nu_har_vi_ljus.typ"
#include "pippis_sommarvisa.typ"
#include "tusen_ljus.typ"
#include "varvindar_friska.typ"
