
#include "avslag_pa_csn.typ"
#include "bredbandshymn.typ"
#include "brev_fran_kongligen.typ"
#include "dance_macabre.typ"
#include "dataeliten.typ"
#include "datalogik.typ"
#include "datas_bordsvisa.typ"
#include "den_kodbestrodde_norden.typ"
#include "du_nya_du_frascha.typ"
#include "en_kvall_i_meta.typ"
#include "ett_noll_ett.typ"
#include "ja_ma_d_leva.typ"
#include "jag_vill_va_som_du.typ"
#include "konglig_datasektionens_sektionssang.typ"
#include "matlab.typ"
#include "meta_nationalsang.typ"
#include "mors_lilla_dator.typ"
// #include "nar_examen_viskar_mitt_namn.typ"
#include "np_inte_p.typ"
#include "prylmanglerister.typ"
#include "systeme_interweb.typ"
#include "the_basic_song.typ"
#include "till_emacs.typ"
#include "write_in_c.typ"
